### ISSUE TITLE
"First cycle start" date does not work

### ISSUE THREAD

**Issue by quartertone** [Futsch1/medTimer#101]
Setting the "First Cycle Start" date in the advanced settings does not appear to do anything. ie - After setting this to a future date, the app still displays a reminder for "today" (missed or future dose).

Also: [feature request] It would be nice to display the First Cycle start date for each item in the medicine list, or in the reminder/dosage cards in the medicine edit view.

**Comment by Futsch1** [comment]
I can confirm that it does not work for future cycle start days, I found the cause and will fix it in the next release.

The feature request will also be part of the next release.
