### ISSUE TITLE
non-free dependency added with latest release

### ISSUE THREAD

**Issue by obfusk** [Futsch1/medTimer#106]
Hi! Using the proprietary `AnyChart` library will result in the `NonFreeComp` anti-feature at @IzzySoft's repo (though I personally would want to avoid any non-FOSS dependencies completely in medical apps like yours). Non-free dependencies are not allowed by F-Droid at all (though I suspect its presence will only be detected when the build fails to be reproducible because of the missing license key).

**Comment by Futsch1** [comment]
I actually didn't anticipate that since AnyChart is open source (even though not under a free license...).

But you are right, this actually breaks reproducible builds and might have been the wrong choice for the app.

I will replace it with androidplot in the next release.

**Comment by obfusk** [comment]
> AnyChart is open source

Unfortunately, whilst the source code is indeed _available_, it is in fact not _open source_; as the [Open Source Definition](https://opensource.org/osd) says:

> Open source doesn’t just mean access to the source code. The distribution terms of open source software must comply with the following criteria: [...] The license must allow modifications and derived works, and must allow them to be distributed under the same terms as the license of the original software. [...]

AnyChart clearly does not comply with those criteria.

**Comment by obfusk** [comment]
> I will replace it with androidplot in the next release.

Thanks!

**Comment by obfusk** [comment]
FYI: IzzyOnDroid had already picked up the v1.8.0 with `AnyChart`. AFAIK the new version should replace that automatically. Luckily, you increased the version code so users that installed that version will get the updated v1.8.0.

F-Droid will likely never notice anything since it never picked up the `AnyChart` release.

Also, Android CI still has the

```
sed -i 's/AnyChartLicenseKey=\(.*\)/AnyChartLicenseKey=${{ secrets.ANYCHART_LICENSE_KEY }}/' gradle.properties
```

**Comment by Futsch1** [comment]
Thanks for the update! I just removed the line from the Android CI and pushed a new version, v1.8.1, which will be then taken over to all stores for sure and no longer contain AnyChart.

Btw, I actually liked androidplotlib a little more ;-)

**Comment by obfusk** [comment]
Good :)

I was a little too optimistic about IoD picking up the updated APK automatically :sweat_smile:

**Comment by IzzySoft** [comment]
Once an APK has been pulled from a release, it won't be pulled again. It takes a new release for that – or manual action on my end…

**Comment by Futsch1** [comment]
I have added the 1.8.1 release afterwards, this does not contain the non-free dependency and is different from 1.8.0 for sure...

**Comment by IzzySoft** [comment]
Yupp. And that has already been pulled; so I only removed the 1.8.0 here, no need to replace its APK at IzzyOnDroid as the next release would push it out of the repo anyway.
