### ISSUE TITLE
same day reminder

### ISSUE THREAD

**Issue by ralmcruz** [Futsch1/medTimer#122]
I can not figure out how to add an reminder to start the same day. Next reminder is always set to next day.

**Comment by Futsch1** [comment]
This is how it is implemented right now: freshly created reminders will first trigger on the next day. So you'd have to wait for one day.

Is this an issue for you?

**Comment by ralmcruz** [comment]
Ok then.

Well in my case I had something to take in the same day, but it is not a big deal really.

**Comment by Futsch1** [comment]
In this case, I won't do any changes.

**Comment by Futsch1** [comment]
Actually, thought about it some more and the change is minor: I will implement it.
