### ISSUE TITLE
More patients possible?

### ISSUE THREAD

**Issue by paulle** [Futsch1/medTimer#123]
Would it be possible to add an option various persons (pacients) ?
I'm refering to the use case if one person is looking for medication of other family members too.

**Comment by Futsch1** [comment]
I see the potential use case, but this would mean a major refactoring of the databases, GUI, app logic etc. Since I aim to keep the app simple, I will not implement this feature request for the time being.

**Comment by paulle** [comment]
Ok, I understand your point.
Thank you
And thank you for your app

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 19. Mai 2024, 08:30, schrieb Florian Fetz :
