### ISSUE TITLE
"Linked" medicine alarm times

### ISSUE THREAD

**Issue by Jakarrrg** [Futsch1/medTimer#131]
It would be very helpful if some medicines could be "linked". For example my father takes one drop from  medicine x at 8 pm, and then another drop from  medicine y, ten minutes after the medicine x (8:10). Now, in many occasions he snoozes the alarm for medicine x for let's say 30 minutes (>8:40). It would be very helpful if medicine y would also snooze automatically for 30 minutes (>8:50) retaining the 10 minute interval from medicine x.

 Also it would be nice if user could choose at the time the alarm rings, or even a few minutes before, for how much time he/she/it wants to snooze the alarm, instead of the preselected from settings snooze time.

**Comment by Futsch1** [comment]
Linking medicines sounds like a fairly complex feature, I will have to think about if and if yes how to implement it.

Custom snooze times should be fairly easy, but I will create a new issue for it to track the progress.

**Comment by Futsch1** [comment]
I decided to implement this feature in the release after the next. I plan to implement it as following:

On the Advanced Settings page of a reminder, there will be a new button to add a linked reminder. This reminder will then make it possible to set a delay time that the linked reminder will trigger after the source reminder. So when the source reminder is marked taken, the delay time for the linked reminder will start.

It will not be possible to set the delay time to a value that would span to the next day, but same day is possible.

This will facilitate the use case that two reminders are taken with a defined delay between them.

**Comment by Arkonos** [comment]
Am I correct in my understanding that only the same medicine, although with a different dose, can be linked?

**Comment by Futsch1** [comment]
That is correct. However, that is currently only a limitation of the UI (if I'm not mistaken), so being able to link doses across medicines could be implemented. If you have the use case, feel free to create a feature request.
