### ISSUE TITLE
Option to edit hour of taken pills

### ISSUE THREAD

**Issue by estux** [Futsch1/medTimer#138]
Hello again, I'm sorry to open more issues but would like to explain also this case that is not considered by the app.
It can happen to skip some pills for some hours (e.g. because you have different day time schedule for some time, as it could happen on vacation or during trips in general) without impacting negatively on your routine of pills intake.
Let me explain it with an example:
**Original plan**
- medicine A, pill at 7:30 (before breakfast)
- medicine B, pill at 8:00 (after breakfast, could be a little later depending on breakfast time that is not strictly fixed)
- medicine C, pill at 10:00 (in the middle of the morning, with quite empty stomach)
- medicine D, pill at 14:00 (after lunch)
- plus some others later that I won't consider here as these are enough to explain my example

**Shifted plan (because of different time schedule on certain days, that could also be e.g. only on sundays)**
- wake up at 9:00
- medicine A skipped
- medicine B skipped
- medicine A registered as additional dose at 9:10
- medicine B registered as additional dose at 9:50
- medicine C reminder at 10:00
- medicine C skipped
- medicine C registered as additional dose at 11:50
- lunch at 13:15
- medicine D reminder at 14:00
- medicine D skipped
- medicine D registered at 15:00

This is how I would register them actually in the app (as it's following a rigid schedule). 
This is not ideal as the app is telling me I'm skipping half the time in graphs but that is not true. It also doesn't make much sense to have double entries for all the pills (skipped first and then registered just a bit later).

For this reason I think the best thing is to let user edit time in history (for already registered events) and/or to consider "skip to take later" case in the notifications. Maybe this flexible behaviour could be activated not by default and only by some people with a flag in the settings (and maybe behind a disclaimer to not use it to skip pills in general as it could be dangerous).

Thank you so much!
I think this could help also others that are using this app.

**Comment by Futsch1** [comment]
Hi estux,

thanks for your suggestion. It is already possible to edit taken doses by right-swiping them in the overview, but it is not possible to edit the time. This can be added, I will work on it.

Furthermore, the app takes note of the time when you actually mark a notification as "TAKEN", so for the time being you could keep the notification active and only select "TAKEN" when you actually took the medicine. The actual taken time will only show in the CSV/PDF export, but I will also add it to the tabular view.

**Comment by Futsch1** [comment]
I was already working on an app intro and have just created an issue for it: #139. This will give hints on the swiping. See also #140 to be able to delete reminder events.

**Comment by estux** [comment]
> I was already working on an app intro and have just created an issue for it: #139. This will give hints on the swiping. See also #140 to be able to delete reminder events.

Great, thank you so much @Futsch1 ! Your work is really appreciated!
