### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by estux** [Futsch1/medTimer#142]
Hello again,
I saw there's values-de but there's no italian translation. 
How can I contribute? Is there an XML file I can easily edit locally and then upload to contribute the italian translation?
Thnak you very much!

**Comment by estux** [comment]
> First: Much appreciated and thanks for your willingness to contribute!
> 
> I have just created a branch with a machine-translated Italian language. You could review and correct it. The Italian language file is located here:
> 
> https://github.com/Futsch1/medTimer/blob/142-italian-translation/app/src/main/res/values-it/strings.xml
> 
> The original English file for reference is here:
> 
> https://github.com/Futsch1/medTimer/blob/142-italian-translation/app/src/main/res/values/strings.xml
> 
> You could either fork the repo and create a pull request based on this branch or (if you are not familiar with git/Github) just edit the Italian XML file and upload it here as an attachment, I will take care of the rest.

You're welcome! :) Thanks for your great work with this app!
Now I feel safer to go with the simple way: download the xml files and contribute uploading the result later, if it's not much added burden for you.
I would gladly try git/Github system but need time and a bit of practice to learn them (will do it soon tough as I like to learn new things :) ).

**Comment by estux** [comment]
> First: Much appreciated and thanks for your willingness to contribute!
> 
> I have just created a branch with a machine-translated Italian language. You could review and correct it. The Italian language file is located here:
> 
> https://github.com/Futsch1/medTimer/blob/142-italian-translation/app/src/main/res/values-it/strings.xml
> 
> The original English file for reference is here:
> 
> https://github.com/Futsch1/medTimer/blob/142-italian-translation/app/src/main/res/values/strings.xml
> 
> You could either fork the repo and create a pull request based on this branch or (if you are not familiar with git/Github) just edit the Italian XML file and upload it here as an attachment, I will take care of the rest.

In the end I decided to learn and to try directly with git/Github...I hope I did all right! :) @Futsch1

**Comment by Futsch1** [comment]
@estux Thanks again for your support. If you want to provide also translated Play Store texts, you can check the files in this folder:

https://github.com/Futsch1/medTimer/tree/main/app/src/main/play/listings

and create a new one for `it-IT`.
