### ISSUE TITLE
Notifications per medication

### ISSUE THREAD

**Issue by jceloria** [Futsch1/medTimer#151]
I group my morning and evening medications, then list what I take in the additional instructions (I also take several health supplements). If I were to list out each, I would get way too many notifications throughout the day. 

It would be awesome if I could set notifications on required medications and different notifications on non critical ones.

MQTT integration for automations would be even better (while I'm wishing :)).

Best medication reminder by far and works perfectly for me as is though, thank you for all of your work.

**Comment by Futsch1** [comment]
@jceloria: Just to make sure that I get this right: A setting per medication if this medication should raise notifications or not would solve your use case?

MQTT sound interesting, but it might have a big catch: Currently, the app does not have permission to access the network (kind of guaranteed privacy). MQTT will most likely require this permission, but maybe this can also be granted dynamically - I'd have to investigate. Would you mind creating a separate issue for the MQTT use case and specify this in a bit more detail?

**Comment by jceloria** [comment]
Sorry for the delay in reply @Futsch1, I'm sorry if I was not more clear in my use case.... For example, I have 5 health supplements that I've grouped into a single medication called `Morning Supplements` and 4 that I've grouped into a single medication called `Evening Supplements` I also have critical pharmaceuticals I take around the same time each day. I have another temporary critical medication that I need to take 3 different times a day, as well as another one that's once a week. Right now, they all have the same notification sound. If there was a say, a default notification like there is now, I could use that for the non-critical supplements. If I had the ability to change the notification sound on the critical pharmaceuticals it would make it easier to identify.

The same goes for any other temporary medication my doctor prescribes to me, I don't always have my phone on me, but its usually within earshot.

Even if this is too much trouble, I still want you to know that this is the best solution I've found and I really appreciate the work that you and everyone else who has contributed.

**Comment by Futsch1** [comment]
I will rework #150: instead of having a global notification priority option, I will add this per medication in the advanced setting.

**Comment by jceloria** [comment]
You're a rockstar, can I send a donation somewhere?

**Comment by Futsch1** [comment]
😊 thanks!

No donations for me, I plan to setup a donation possibility for charity, but haven't done this yet.

I changed it to a setting per reminder and will do the release likely tomorrow.

**Comment by Futsch1** [comment]
After a good night's sleep, I reconsidered it and moved the setting to the medicine as originally planned. Will still release today ;-)

**Comment by Futsch1** [comment]
@jceloria See details here: https://github.com/Futsch1/medTimer/discussions/161
