### ISSUE TITLE
hiding confirmed or skipped entries

### ISSUE THREAD

**Issue by fase1** [Futsch1/medTimer#166]
it would be great to have the possibility to select hiding of confirmed and skipped entries, so just not defined / forgotten ones are visible in the history in better overview

**Comment by Futsch1** [comment]
This applies to the overview screen, right?

I understand the suggestion and will implement it in one of the next releases (given I can think of a nice way to add it to the UI that does not clutter the view to much)

**Comment by fase1** [comment]
exactly, the overview.
that would be perfect, many thanks in advance
