### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Futsch1/medTimer#169]
ref: https://monitor.f-droid.org/builds/log/com.futsch1.medtimer/56#site-footer

something changed in the tooling you (and others use to build the apps), we've gathered the ever increasing list of apps that are otherwise reproducible yet their APKs are not here: https://gitlab.com/fdroid/fdroiddata/-/issues/3299

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/15d177e807fc64a3bf8835b1f7c9f623643ad7bc

**Comment by Futsch1** [comment]
I see that this is a tooling issue related to the update of the Android SDK to version 35 in the Github Ubuntu image. So it's obviously not related to a change I made.

Is there anything I can do to support? Try an older Ubuntu image?

**Comment by licaon-kter** [comment]
Does the Ubuntu image hold older build-tools versions?

eg. in https://github.com/Futsch1/medTimer/blob/v1.8.10/.github/workflows/android.yml#L79

instead of `${{ env.BUILD_TOOLS_PATH }}/apksigner` maybe use `/usr/local/lib/android/sdk/build-tools/34.0.0/apksigner` ? :shrug:

**Comment by Futsch1** [comment]
That's actually working, so 34.0.0 is installed:

`Run /usr/local/lib/android/sdk/build-tools/34.0.0/zipalign -v 4 $APK_RELEASE_DIRECTORY/MedTimer-release-unsigned.apk \`

I will create a new tag/version to check if this resolves the build issue

**Comment by obfusk** [comment]
Downgrading should work, but isn't ideal. I listed the 3 possible ways to fix this issue here: https://github.com/obfusk/apksigcopier/issues/105#issuecomment-2206799316

**Comment by Futsch1** [comment]
I see, thanks for the hint. I will look into your other two proposals and choose one of them for a more sustainable solution.

**Comment by obfusk** [comment]
You're welcome. And good luck. The 2nd option would be a fix on your end, the 3rd one on F-Droid's.

I worry that there isn't really a sustainable solution for F-Droid running a Reproducible Builds project when they no longer have an expert to fix things when they break or anyone having a proper understanding of all the tooling they depend on.

But I [resigned from F-Droid last year](https://gitlab.com/fdroid/admin/-/issues/447) so it's not my problem any more 🤷‍♀️

**Comment by obfusk** [comment]
Also, FYI your unsigned and unsigned-aligned APKs are completely identical. Android Gradle Plugin has been producing aligned unsigned APKs for years so running `zipalign` doesn't really do anything.

**Comment by licaon-kter** [comment]
I've seen the zipalign command in many Github CIs, I guess that's a template added there years ago that keeps getting copied without reasoning. :))

**Comment by obfusk** [comment]
> I've seen the zipalign command in many Github CIs, I guess that's a template added there years ago that keeps getting copied without reasoning. :))

Yeah, I'm sure it used to be needed with older AGP versions. Luckily it's just redundant now, not doing any harm :)

You on the other hand seem to have been calling `zipalign` with completely nonsensical options. I guess you didn't realise the difference between the regular byte-alignment parameter (which -- as both the Debian man page and Android docs state -- is always set to 4, never anything else -- which does make it quite odd that it's a mandatory argument (except in my `zipalign.py` Python implementation) :woman_shrugging:) and the recently added `-P` option (which Debian's `zipalign` is too old to support) to set the page alignment for `.so` files (which used to be hardcoded as 4k but now defaults to 16k in e.g. AGP, with 4k and 64k also being valid)?

**Comment by licaon-kter** [comment]
>  I guess you didn't realise the difference between the regular byte-alignment parameter

that got lost on the way, for these cases, as I went in and out of used tools

> as both the Debian man page and Android docs state -- is always set to 4, never anything else 

what's more funny is that feeding it 16 or 64 yields different files, but more so confusingly, yields consistent files for these values

**Comment by obfusk** [comment]
> what's more funny is that feeding it 16 or 64 yields different files, but more so confusingly, yields consistent files for these values

Yes? That would be neither odd, not confusing, but entirely expected. It's doing exactly what you told it to do: add padding for alignment to 16/64 bytes instead of 4. It's not in any way *useful* to align to anything but 4 bytes though.

**Comment by obfusk** [comment]
As I pointed out, if you don't understand what changes tooling like `zipalign`, `apksigner`, `repro-apk`, etc. make to the APK, you will not be able to fix anything if it breaks because something changed in the toolchain like here. Except by downgrading or getting lucky with trial and error of various options you happen to know about. Hoping someone else fixes it for you seems like a bad strategy :woman_shrugging:

**Comment by Futsch1** [comment]
> > I've seen the zipalign command in many Github CIs, I guess that's a template added there years ago that keeps getting copied without reasoning. :))
> 
> Yeah, I'm sure it used to be needed with older AGP versions. Luckily it's just redundant now, not doing any harm :)
> 
> You on the other hand seem to have been calling `zipalign` with completely nonsensical options. I guess you didn't realise the difference between the regular byte-alignment parameter (which -- as both the Debian man page and Android docs state -- is always set to 4, never anything else -- which does make it quite odd that it's a mandatory argument (except in my `zipalign.py` Python implementation) :woman_shrugging:) and the recently added `-P` option (which Debian's `zipalign` is too old to support) to set the page alignment for `.so` files (which used to be hardcoded as 4k but now defaults to 16k in e.g. AGP, with 4k and 64k also being valid)?

Then the guy where I copied it from obviously had no clue about it ;-)

Jokes aside, I will remove the call to `zipalign` anyway.

**Comment by obfusk** [comment]
I added a FAQ entry with more details: https://github.com/obfusk/apksigcopier#what-about-signatures-made-by-apksigner-from-build-tools--3500-rc1

**Comment by licaon-kter** [comment]
Latest tag should be 1.16.9 not 1.6.9

**Comment by Futsch1** [comment]
Arg, such a stupid mistake. Will fix as soon as I can.

**Comment by Futsch1** [comment]
@licaon-kter apparently, F-Droid stopped picking up new tags in this repo starting from v1.16.10 and only restarted with v1.17.0. Is this a consequence of the wrong tag name for V1.16.9 or is there another issue?

**Comment by licaon-kter** [comment]
@Futsch1 I think it was glitch in the checkupdate pipeline, that we fixed back in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/21350
