### ISSUE TITLE
attach_hotspot_windows.dll inside APK

### ISSUE THREAD

**Issue by licaon-kter** [Futsch1/medTimer#170]
in `win32-x86` and `win32-x86-64` folders

why?

**Comment by Futsch1** [comment]
This is obviously part of kotlinx-coroutines-debug (https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-debug/). I suppose I don't need it, will check and remove if possible.

**Comment by Futsch1** [comment]
Ok, the mistake was that I added mockito-core as an implementation dependency and not as a testImplementation dependency. With this change, the folders are gone.
