### ISSUE TITLE
"Taken" action when dismissing notification

### ISSUE THREAD

**Issue by ZeusOfTheCrows** [Futsch1/medTimer#178]
[Request/Enhancement]

Add "Taken" to list of options available when dismissing a notification in settings

(I'd guess "Taken" is the most common action, and it's quicker to swipe a notification away than hit a touch target)

**Comment by ZeusOfTheCrows** [comment]
may i just say: i looked through old issues before opening this to check it wasn't a duplicate, and i couldn't help but notice how great you've been at implementing requested features - thank you for your work maintaining this app!

**Comment by Futsch1** [comment]
Thanks for the feedback, I appreciate it! It's just a pleasure to work on the app and it is nice that it helps people!
