### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by stepanzubkov** [Futsch1/medTimer#194]
I like this app so much and would like to translate it to my native language. Is it possible right now?

**Comment by Futsch1** [comment]
Yes, sure. Either paste the strings.xml here and I will integrate it or fork and PR.

**Comment by Futsch1** [comment]
Be aware that I just merged a PR that contains some minor changes in the strings.xml, so you might want to update your fork.

**Comment by stepanzubkov** [comment]
Ok, I understand
