### ISSUE TITLE
No Date selection when recording a past dose

### ISSUE THREAD

**Issue by realrandolph** [Futsch1/medTimer#201]
When recording a past dose of a medication, the time can be selected but the date cannot. This would be useful for medications that are 'take as needed' which the user forgot to record (for instance, if they took a sleep medication before bed), or which they've only just added reminders for.

**Comment by Futsch1** [comment]
The reason here is that the date recorded is important for the calculation of the next dose, changing this would mess up the algorithm (as it is implemented now).

However, I will make the date editable for manually logged doses.
