### ISSUE TITLE
Meds taken past midnight cause issue for next days dose

### ISSUE THREAD

**Issue by realrandolph** [Futsch1/medTimer#205]
I'll explain with an example. If a medication is scheduled for 11PM, and the user marks the medication as taken later (after midnight), then it seems it counts that 'taken' towards the next day's dose when that dose is scheduled. 

[Here is a screenshot](https://i.imgur.com/dZvQNzU.png) of what I mean. At the top of the list is what should be the dose for the 25th (which has not yet been taken nor even have we reached the dose time), but it is recorded as taken from when the previous day's dose was recorded.

**Comment by Futsch1** [comment]
Hm, this was fixed in #181 (v1.8.13). Can you check which version you are using? How did you mark the dose taken (via the notification or the overview)? Did you use snooze?

**Comment by Futsch1** [comment]
I was able to reproduce it. So I will work on a fix.
