### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [Futsch1/medTimer#22]
Just wondering that the app description says

> All data is stored securely on your device, ensuring complete privacy and offline accessibility. No internet connection required – your medication reminders are always available.

But then, the app requests the permissions `INTERNET` and `ACCESS_NETWORK_STATE`. How does that match? Can you please clarify? Thanks in advance!

**Comment by Futsch1** [comment]
Both permissions are not required from the app, but from used libraries. The features in those libraries requiring internet access are not used. You can validate this by checking the data usage of the app in the app info menu.
![Data usage](https://github.com/Futsch1/medTimer/assets/63090558/f121714a-1b99-4ce3-a31f-9af1a37abcdb)

The INTERNET permission results from the use of https://github.com/wwdablu/SimplyPDF - an open source library to create PDF documents in Android. It has the possibility to create PDFs from JSON files where images can be embedded as URLs. The app does not make use of this, but the library requires it nonetheless.

**Comment by IzzySoft** [comment]
If they are not used, can't you remove them? See e.g. [Removing Unwanted Manifest Permissions With tools:node](https://developermemos.com/posts/removing-unwanted-manifest-permissions/)

**Comment by Futsch1** [comment]
I did not know that tool, thanks a lot for pointing it out! I will remove the permissions from the app.

**Comment by IzzySoft** [comment]
Thanks! I also learned about it only recently.
