### ISSUE TITLE
Add option to set start and end date of a reminder

### ISSUE THREAD

**Issue by bo-hmpl** [Futsch1/medTimer#221]
Tbh, I'm not sure whether that's a bug or if I just don't get this feature right:

I take a medicine with a plan for tapering it off. Meaning e.g., I start at 01/08 with 40 mg, three days later at 04/08 I reduce the dose to 30 mg, a week later to 20 mg and so on. So I've set different reminders for this medicine, each cycle starting at the respective date with a number for "Active days", like 3 or 7. But still I receive every day a message for every single reminder of that one medicine, even those that should start in the future and those that should have ended after the number of active days.

If that's the intended behaviour, I'd need an explanation how "Cyclic reminders" is to be used.
In that case I'd suggest a feature where one can exactly set up a period of time when a medication plan starts and ends.

**Comment by Futsch1** [comment]
This is indeed working as intended: The start date is just the first day of the cycle, the app projects the cycle backwards and forwards in time. So this function does not work to plan tapering off a medicine.

However, I will use your feedback to implement a setting that would work for your use case: The option to set a start and/or end date of a reminder.

**Comment by bo-hmpl** [comment]
Alright, that makes sense. Admittedly, this is a bit confusing having a start date when it's actually a permanent cycle.
Thank you for considering adding such an option!
