### ISSUE TITLE
Amoled theme support 

### ISSUE THREAD

**Issue by Zaxx69** [Futsch1/medTimer#23]
Please add a amoled theme for the app

**Comment by Futsch1** [comment]
The app already has a dark/night mode theme, that's what you meant?

![Dark mode](https://github.com/Futsch1/medTimer/assets/63090558/4eaf174d-8cb4-4da8-a13b-ac56c3c47315)

**Comment by Zaxx69** [comment]
I meant full black theme

**Comment by Zaxx69** [comment]
![Screenshot_2024-03-15-12-20-00-32_a5af3585a93e2016f6667aaf7e1e2f32.jpg](https://github.com/Futsch1/medTimer/assets/138523882/aebdc1df-3cdc-4244-baf7-ddc04e0372e6)
