### ISSUE TITLE
notificación with a nagging sound

### ISSUE THREAD

**Issue by paulle** [Futsch1/medTimer#237]
As I don't look always at my cellphone it would be nice to have the option to have the notification with a really nagging sound for not miss a medication.

**Comment by Futsch1** [comment]
You can select a custom notification sound for reminders: One for standard priority medication and one for high priority medication. See here for a description: https://github.com/Futsch1/medTimer/blob/main/app/doc/UseCases.md#different-notification-sounds

**Comment by paulle** [comment]
Thank you for your hint.
