### ISSUE TITLE
Reminder: Every second day

### ISSUE THREAD

**Issue by OneCreek** [Futsch1/medTimer#24]
I would need the reminder to be set only for every second day. 

Could this be included in a future release?:)

The best, Michael

**Comment by Futsch1** [comment]
Yes, I'll work on that in the coming weeks.

**Comment by OneCreek** [comment]
Works great with 1.3.0. thanks a lot.
Still I think the naming could be improved. It still says 1 reminder/day instead of reminder every 2 days. 
![Screenshot_20240322-052939.png](https://github.com/Futsch1/medTimer/assets/107502675/0b934908-17a9-4e52-8449-def534dfc232)
