### ISSUE TITLE
I can't able to install this app

### ISSUE THREAD

**Issue by rsaurav12** [Futsch1/medTimer#242]
Devices spec:
Miui 14
Android 12

![Screenshot_2024-09-13-05-51-01-085_com android vending](https://github.com/user-attachments/assets/c913ba17-0949-4511-bc98-3222ab25a167)
![Screenshot_2024-09-13-05-50-42-276_com google android packageinstaller](https://github.com/user-attachments/assets/230ffff6-fa7d-4418-9eb7-eec3ced6a19f)

**Comment by Futsch1** [comment]
The app requires Android 13 to run, so unfortunately, it is as the screenshot says: Your device isn't compatible with this app.
