### ISSUE TITLE
Edit reminders from tabular view

### ISSUE THREAD

**Issue by erflaber** [Futsch1/medTimer#249]
I'm experiencing an issue with editing past medication reminders. Here's the scenario: 

1. I have a daily medication reminder set up.
2. I forgot to take the medication one day, and now I want to edit the reminder for that specific day.
3. However, when I click on the reminder, it brings me to today's reminder instead of the original one I missed.
4. The original reminder still appears in my notifications, but I'm unable to edit it.

     

This is causing me to have outdated notifications that I cannot update or dismiss. I'd like to be able to edit past reminders to keep my medication schedule accurate. Is there a way to achieve this that I am missing?

**Comment by Futsch1** [comment]
The overview screen will show the reminders for the past day per default. In the settings, you can change this interval to a maximum of seven days: 
![image](https://github.com/user-attachments/assets/52f87678-4184-4448-aec5-236b8e2a8054)


Now, you would be able to see not only today's reminders, but those seven days past.

Would this solve your issue?

**Comment by erflaber** [comment]
Yes, it did. Wonderful! Thank you!

Now, I realize that this was causing me a disproportionate amount of anxiety (side thought: hm, did I take my meds today? (side side thought: I do have a problem with side thoughts)).

It would be cool if there was a way to edit the entries in the tabular view.

**Comment by Futsch1** [comment]
I agree, this would be a nice addition. I'll keep the issue open to track the implementation of it.
