### ISSUE TITLE
Question on translation

### ISSUE THREAD

**Issue by k2helix** [Futsch1/medTimer#27]
Hi, I installed medTimer recently and noticed that there's no option to change the app language directly. 

When I searched through the source code to find the strings.xml file, I saw that there is a `values-de` which contains the strings translated to German. 

I was wondering if it was planned to let the user choose a language from the ones that are available. 

Thanks.

**Comment by Futsch1** [comment]
The app will adapt to the system language. However, I might easily add a preference to change the language, so I will plan to implement it.

**Comment by k2helix** [comment]
I see. So I can PR a new translation right?

**Comment by Futsch1** [comment]
Yes, would be very much appreciated! I planned to look into AI translation, but a human made one will certainly be better!
