### ISSUE TITLE
Repeat an alarm unless taken

### ISSUE THREAD

**Issue by AlbeyAmakiir** [Futsch1/medTimer#320]
I'd like the option for my med alarm to repeat fire every X minutes until I mark the med as taken or skipped (or snoozed if that's ever an option), or until the alarm has fired Y times.

I use this feature in Medisafe as my ADHD makes it really easy for forget to take my meds even if I hear the alarm the first time.

The only app I've seen do this is Medisafe, where I'm using the default: every 10 minutes for 4 attempts, that is, 3 after the initial one (30 mins), but that app is about to undergo enshittification and I must move from it.

**Comment by Futsch1** [comment]
I will implement this in the next release
