### ISSUE TITLE
Top bar seems to use the wrong color

### ISSUE THREAD

**Issue by dr460nf1r3** [Futsch1/medTimer#34]
Hi! 
Thanks for this great app. It seems to be the only one of its kind to make use of Material You from what I've seen. 

There is one issue with the colors:
![Screenshot_20240318-103214_MedTimer.png](https://github.com/Futsch1/medTimer/assets/12834713/50c5f4e1-10d1-4be1-849b-cacd6cb414de)

The top bar seems to use the wrong color. Exemplary Fossify Gallery Screenshot:

![Screenshot_20240318-103429_Gallery.png](https://github.com/Futsch1/medTimer/assets/12834713/2132a567-b168-4b68-bab2-67fd93379667)

If possible, the same color should be used for the top bar and the content below so theming looks more consistent.

Thanks! :)

**Comment by Futsch1** [comment]
I am using Material3.DynamicColors theme with default settings. 

This theme defines the statusBarColor as `colorPrimary` (a color that is derived from the current launcher background image/color) and the app bar color as `surface`. I personally like the look of the theme - so it's no bug, but a feature ;)

**Comment by dr460nf1r3** [comment]
So it is a design choice, I see. Can we make this a feature request for another theme choice then? :)

**Comment by Futsch1** [comment]
Accepted - I will work on it.
