### ISSUE TITLE
Support older phones that aren't being updated any more

### ISSUE THREAD

**Issue by AlbeyAmakiir** [Futsch1/medTimer#340]
Phones are being forced into planned obsolescence by no longer receiving updates.

Google is enforcing that newer apps can't run on older phones even if they should be able to, and requiring that apps on the play store continue to update their target sdk and the like or risk being booted from the play store.

How low can you set the target sdk (or related) without losing features you make use of nor losing the ability to use the play store?

**Comment by Futsch1** [comment]
I totally understand your request, but the effort for this would be too high. For a more detailed justification, see #41 .

**Comment by AlbeyAmakiir** [comment]
Understandable. Thanks for explaining
