### ISSUE TITLE
Allow users to edit past Doses

### ISSUE THREAD

**Issue by Mohl** [Futsch1/medTimer#341]
**Is your feature request related to a problem? Please describe.**
Doses might be marked as "Taken" by accident, or Doses might be taken but not marked as "Taken" right away. This leads to poor data quality and skews the statistics ( especially if doses need to be taken at a specific point in the day ) and hinders proper adherence monitoring.

**Describe the solution you'd like**
- Allow unchecking of "Taken" doses:
Upon tapping the "Taken" Button of an already taken Dose in the "Recent events" Panel, Users might be presented with a pop-up:
"Mark dose as untaken?". Upon confirming, the reminder for the given event will be recreated and the entry for this dose will be deleted from the log.

- Allow editing of entries of past doses:
Upon long-pressing on an entry in the "Recent events" panel, users will be presented with a screen that allows editing the entries of this dose, like timestamp, amount taken, and the "Taken" / "Skipped" Flags. Upon saving, the status will need to be recalculated.

**Comment by Futsch1** [comment]
Editing past doses is already possible; not by long-press, but by swiping. Changing the taken/skipped flag is also already possible from "Recent events".

Marking a dose as "untaken" is a good addition, I will implement it.

**Comment by Futsch1** [comment]
I think I'll be able to start working on it this weekend. If you want to contribute, you might also want to consider #298
