### ISSUE TITLE
First cycle date decremented

### ISSUE THREAD

**Issue by bundle359** [Futsch1/medTimer#355]
**Describe the bug**
With certain actions in the advanced setting, the first cycle start will be decremented by one day. It always occurs for me with the date menu, so I have to select a date one day in the future. I've also noticed this occurs when i press the back button in the advanced settings menu, so I've stop using that. I can return by tapping the medicine icon.

**To Reproduce**
1. Go to Advance Settings for a reminder
2. Select a first cycle start date and confirm
3. See that that the date is change by one day previous
4. Press the back button in the top left of the settings menu
5. See that the start date is decremented by an additional day

**Expected behavior**
The dates don't change unless selected.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - Android version: Android 15. I'm using GrapheneOS.

**Additional context**

**Comment by Futsch1** [comment]
Can reproduce it, it seems related to time zones. I will fix it in the next release.

**Comment by bundle359** [comment]
thanks for fixing!
