### ISSUE TITLE
Calender view + med Stock [Feature Request]

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [Futsch1/medTimer#48]
@Futsch1 Thanks for the app, I'd like to request the implementation of two key features to enhance medication management: **Calendar View and Med Stock Integration**. These features would greatly improve the usability and effectiveness of the app in helping users like me stay organized with their medication schedules and supplies.

**### Calendar View**:
I envision a feature where users can easily visualize their medication schedules across different time frames, such as daily, weekly, and monthly views. This Calendar View would allow users to see upcoming doses, track past administrations, and anticipate any changes in their medication regimens effortlessly.
 **### Med Stock functionality** :
 This feature would provide users with real-time information about their medication inventory, helping them stay informed about their supply levels and ensuring they never run out of essential medications. 
**Inventory Monitoring**: The ability to view current medication stock levels alongside the calendar interface, allowing for easy tracking of medication supply.
Automatic **Refill Reminders**: The app should generate refill reminders based on medication consumption patterns and remaining stock levels, helping users avoid interruptions in their treatment plans.
**Insights and Analytics**: Access to insights regarding medication usage trends, empowering users to make informed decisions about refills and prescription management.

**Comment by Futsch1** [comment]
Thanks a lot for your feature request!

I have already planned to add an overview table of past doses, which might cover some of the use cases you mentioned in Calendar View.

The second suggestion to support the management of medication inventory is currently a low prio topic which I might consider some time in the future - right now, I'd like to focus on the core feature of medication reminders and exporting the medication history.

**Comment by Futsch1** [comment]
All aspects that I wanted to implement have been added in v1.8.0

**Comment by Bhardwaj10Ankit** [comment]
Thanks a lot for 🙏🏻
