### ISSUE TITLE
Export/import med settings/data plan

### ISSUE THREAD

**Issue by OneCreek** [Futsch1/medTimer#49]
Unfortunately the app (1.4.2) crashed at one point so bad, that all reinstalling didn't help. Not sure if it was a Xiaomi issue. First notifications stopped. Then after checking and editing some energy saving mode, the app didn't start any more at all. 

What helped was a simple uninstall and install.

To prevent in the future a full new creation and configuration of the medication plan, a Export/import function would really be helpful.

Thanks, Michael

**Comment by Futsch1** [comment]
I am sorry that the app stopped working on your device. I haven't experienced a similar behavior and have not yet received any crash reports via the Google Play dashboard.

However, I will look into your feature request to support an export and import of the settings in one of the next releases.

**Comment by OneCreek** [comment]
Was installed via f-droid and crash log was only provided to be sent to Xiaomi... If it happens again (which we don't hope) I can provide the log as well. 

Anyway, thanks for considering the feature request! :)
