### ISSUE TITLE
Feature Request: Irregular acceptance as required 

### ISSUE THREAD

**Issue by Django-BOfH** [Futsch1/medTimer#50]
A function for documenting irregularly required medication, such as painkillers, using the app would be very helpful and desirable.

**Comment by Futsch1** [comment]
I see your use case and will implement this in one of the next releases.

**Comment by Django-BOfH** [comment]
I'm pleased that you want to implement the function. At the moment, the whole procedure is a bit awkward for me. OK. Ibuprophen is always stored in the app. If I'm in an awkward situation, I enter the amount - i.e. 800 mg - and set the time to 1 minute in the future. If the alarm message appears, I can confirm the intake and then delete the time again. OK, in the worst case I have to do this twice a day, if I'm lucky never once a day. This way I have a medication plan to show the doctors what I have taken in the last few days/weeks. Yes, it works that way, but it's still a bit awkward, hence my enquiry to you about this function.


My the way, do you have something like a paypal-account where people can send you something or alternatively a postal address for a parcel/package? 😎

**Comment by Futsch1** [comment]
Just implemented the feature and will upload it to the store right now.

There is no need to donate, I'm doing this purely for fun and educational purposes - happy if the app helps you!
