### ISSUE TITLE
Feature: Nagging notifications

### ISSUE THREAD

**Issue by deadcombo** [Futsch1/medTimer#51]
Hello, thank you for sharing your app.

I frequently put off acting on the notifications, having them repeat periodically until acknowledged would be excellent.

Thank you.

**Comment by Futsch1** [comment]
So the idea of dismissing notifications is that this implicitly marks the reminder as skipped (meaning you did not take the medication).

However, I get your point and see the potential use case. I will make the notification system more configurable in the future, supporting both the original and your use case.

**Comment by deadcombo** [comment]
Cheers. If you'd like it can work as an addition rather than an alternative. Notification keeps going every x minute until you swipe it away.

I've seen some other apps do it, don't know if it's hackish.
<https://github.com/felixwiemuth/SimpleReminder>

<https://github.com/citiususc/calendula>

Calendula is a nice app feature-wise, shame it's abandoned. The alarms don't work anymore and the notifications are a bit unreliable.
