### ISSUE TITLE
Support for birth control pill schedules

### ISSUE THREAD

**Issue by Derkades** [Futsch1/medTimer#52]
Thank you for making this app. What would make it even better is support for birth control pill schedules which are every day 3 weeks on 1 week off. It's a lot more complex than a fixed interval so I'm not sure how it'd fit in the current interface.

**Comment by Futsch1** [comment]
I think it could be implemented by configuring the number of days to pause between reminders (already there) and configuring the number of consecutive reminders (new setting). So if you set the pause to 7 days and consecutive reminders to 21 days, it should work.

However, if a pill has been forgotten, it might get mixed up and you'd need a setting to "reset" the schedule - it might work if this always sets the schedule back to the first consecutive reminder.

Might this be a working solution for you? Or are there any other constraints to take into account?

**Comment by Derkades** [comment]
Thank you! I will ask my girlfriend if this works for her

**Comment by Futsch1** [comment]
You're welcome! I will release the new version today, Google and F-Droid will do the roll out at the latest until the beginning of next week.
