### ISSUE TITLE
Still Version 1.4.2 on F-Droid

### ISSUE THREAD

**Issue by Django-BOfH** [Futsch1/medTimer#61]
F-Droid still only shows me version 1.4.2 and not the current bugfix version 1.5.1. Can you please check why the current version is not displayed for updating? Please, thank you!

**Comment by Futsch1** [comment]
F-droid takes a while to process new updates, see here:

https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

I cannot speed up this in any way, F-droid will just cyclically poll this repo for new releases, build and update them.

**Comment by Futsch1** [comment]
And v1.4.2 will work again without issue. The problem only affected notifications on Sunday.

**Comment by Django-BOfH** [comment]
O.K. I've reinstalled the app and I hope it will work as expected now.

**Comment by IzzySoft** [comment]
@Futsch1 speaking of update cycles: your app is still listed at IzzyOnDroid. Shall it be kept here? Thanks to your having reproducible builds established, switching between the two is easily possible. If you want to have it kept at IoD, you're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there, too :wink:

**Comment by Futsch1** [comment]
@IzzySoft sure keep it there, I just added the badge in the latest PR! Thanks for hinting at this.

**Comment by IzzySoft** [comment]
Thanks! Updated the config accordingly.
