### ISSUE TITLE
Possibility of lowering minSdk?

### ISSUE THREAD

**Issue by k2helix** [Futsch1/medTimer#65]
I wanted to install the app in a device running Android 12 and found out it's not supported. Would it be fairly easy to support a wider range of android versions or is it really necessary?

**Comment by Futsch1** [comment]
I used the latest features of the Android SDK, so unfortunately I cannot lower it without significant changes... see also #41

**Comment by k2helix** [comment]
I see, makes sense. Sorry for creating another issue, I didn't see there was one already closed.
