### ISSUE TITLE
app is closed

### ISSUE THREAD

**Issue by FritzFranuz** [Futsch1/medTimer#67]
Same seconds after leaving the app I  get a popup with the information that the app is closed because of a problem and I should wait for a new version to install .
I just have had a look on my medication and did no changes in the app before. This happens now every day .
I cannot find the Problem.
Do others have the same issue ?

**Comment by Futsch1** [comment]
Which version are you using? Have you tried restarting your phone?

**Comment by FritzFranuz** [comment]
Thank you for quick reaction !
Restart did not solve the Problem, I use  Fdroid repository Version 1.5.1.

**Comment by Futsch1** [comment]
Ok, that explains it: there was an issue introduced with v1.5.1 which caused crashes. v1.5.2 fixes it, but this may take a few days to be rolled out to F-Droid - unfortunately, I cannot influence that...

**Comment by FritzFranuz** [comment]
Ok , thank you!

**Comment by Futsch1** [comment]
So v1.6.0 is now active on F-Droid, but they have a tremendous timing in picking just the bad releases: This version crashes when a reminder is being created. So wait for v1.6.1 to try again.

Sorry for the inconvenience, I will work on my testing coverage to make sure future app updates will be more stable!

I will keep this issue open until v1.6.1 is available on F-Droid.

**Comment by Futsch1** [comment]
v1.6.1 is now available on F-Droid
