### ISSUE TITLE
notifications twice a week 

### ISSUE THREAD

**Issue by FritzFranuz** [Futsch1/medTimer#68]
New can I set two notifications a week, for example Monday and Thursday?
I tried to use two different notifications each every 7 days but I could not set the different day to start. Is there a solution ?
Thanks .

**Comment by Futsch1** [comment]
No, there is no solution yet. I will add the feature to the backlog and implement it in a future release.

**Comment by FritzFranuz** [comment]
Thank you!

Am 6. April 2024 09:17:14 MESZ schrieb Florian Fetz ***@***.***>:
