### ISSUE TITLE
Reminder: certain days a week

### ISSUE THREAD

**Issue by OneCreek** [Futsch1/medTimer#82]
I already had this issue raised https://github.com/Futsch1/medTimer/issues/24 and I'm very happy about the new implementation. 

I don't know if it's possible, but what also would be great is to say: I'd like to take this medicine twice a week on certain days. 
Like Monday and Friday. Here the implementation of https://github.com/Futsch1/medTimer/issues/24 wouldn't really work. 

I'm not sure it is as easy to implement as the rest. And it's not very urgently needed. But still something that would be nice if it's somehow possible to implement.

Thanks already for all your great work!
The best, Michael

**Comment by Futsch1** [comment]
This already works with v1.7.0 (see #68).

In the advanced settings, you will find a button labeled "Remind on". It is per default set to "every day" and will display a list of weekdays to check when selected (see https://github.com/Futsch1/medTimer/blob/main/app/src/main/play/listings/en-US/graphics/phone-screenshots/4.png).

**Comment by OneCreek** [comment]
@Futsch1 oh great thanks!

So in your example when saying "remind 2 executive days and then pause 2 days" and for example I only select one week day e.g. Monday...
Isn't this contradictory?
In that case I would need to select every weekday to get the 2 days and 2 pause?

On the contrary, if I like to be reminded every Monday and Thursday, I should set something like "remind every day and pause 0 days"?
Otherwise I get complimented intersections I guess?

**Comment by Futsch1** [comment]
Yes, combining cyclic reminders with weekdays will result in hard to predict outcomes and will not make sense in most use cases I guess. So I wouldn't call it contradictory, but just not a good idea.

However, since it was easier to implement both at the same time, I did not go for a GUI that makes these two settings exclusive.

**Comment by OneCreek** [comment]
> However, since it was easier to implement both at the same time, I did not go for a GUI that makes these two settings exclusive.
@Futsch1 makes sense. Thanks for clarifying:)
