### ISSUE TITLE
Text not complete visible

### ISSUE THREAD

**Issue by paulle** [Futsch1/medTimer#83]
As you can see in the screenshot text is not complete visible. I'm using a sony experia 5 V. The display has 1080x2520 pixels and a 21:9 ratio.
Android 14.
![Screenshot_20240415-121623](https://github.com/Futsch1/medTimer/assets/4852079/b4a3f9d4-97e6-495f-85fd-991fe84651a4)
Thank you for this good app.

**Comment by Futsch1** [comment]
Thanks for the bug report, I will fix this in the next release
