### ISSUE TITLE
[feature request] interval based reminders

### ISSUE THREAD

**Issue by quartertone** [Futsch1/medTimer#93]
It would be great to have interval based reminders.

Eg:
reminder every 6 hours;
starting from ___date at ___time;
(no reminders between ___-___ times)

**Comment by Futsch1** [comment]
Unfortunately, this collides with the basic concept of reminders in MedTimer: They are triggered on a day basis, not on a delta time basis. 

So if you want a reminder every 6 hours, you'd have to create one for 0:00, 6:00, 12:00 and 18:00 inside one medicine.
